"""added knownas column in Author table

Revision ID: 19100729e30b
Revises: e071b7fcfbae
Create Date: 2024-08-08 15:56:55.063756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19100729e30b'
down_revision = 'e071b7fcfbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knownas', sa.String(), nullable=True))
        batch_op.drop_index('fullname_idx')
        batch_op.drop_index('penname_idx')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('author_idx')
        batch_op.drop_index('title_idx')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_index('publ_name_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index('publ_name_idx', ['publ_name'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('title_idx', ['title'], unique=False)
        batch_op.create_index('author_idx', ['author'], unique=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index('penname_idx', ['penname'], unique=False)
        batch_op.create_index('fullname_idx', ['fullname'], unique=False)
        batch_op.drop_column('knownas')

    # ### end Alembic commands ###
