"""changed isbn to isbn10 in Book model

Revision ID: 21c61b520c9f
Revises: a9ab69a7b378
Create Date: 2024-07-22 14:34:52.210383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c61b520c9f'
down_revision = 'a9ab69a7b378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn10', sa.String(), nullable=True))
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('isbn10')

    # ### end Alembic commands ###
