"""changed first_publish to string in Book model

Revision ID: 44d403843f2e
Revises: 4a3259604a7a
Create Date: 2024-07-26 15:26:41.952540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d403843f2e'
down_revision = '4a3259604a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('first_publish',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index('books_author_idx')
        batch_op.drop_index('books_first_publish_idx')
        batch_op.drop_index('books_title_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('books_title_idx', ['title'], unique=False)
        batch_op.create_index('books_first_publish_idx', ['first_publish'], unique=False)
        batch_op.create_index('books_author_idx', ['author'], unique=False)
        batch_op.alter_column('first_publish',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
