"""added pages summary and genre fields in Book

Revision ID: 4a3259604a7a
Revises: 21c61b520c9f
Create Date: 2024-07-23 17:59:11.316094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3259604a7a'
down_revision = '21c61b520c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penname', sa.String(), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('genre')
        batch_op.drop_column('pages')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('penname')

    # ### end Alembic commands ###
