"""added city field in Author and fixed some bugs in search engine

Revision ID: 572580b89719
Revises: 775a8dc40ca7
Create Date: 2024-07-20 13:48:55.654680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572580b89719'
down_revision = '775a8dc40ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
