"""changed email nullable to true in Author

Revision ID: 62de42483cf1
Revises: 3ad0a81046f9
Create Date: 2024-07-19 04:01:34.010309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62de42483cf1'
down_revision = '3ad0a81046f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
