"""added closed and summary column in Publisherr table

Revision ID: 6b7bef7bfccd
Revises: 19100729e30b
Create Date: 2024-08-12 01:33:48.580316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7bef7bfccd'
down_revision = '19100729e30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('idx_author_country')
        batch_op.drop_index('idx_author_fullname')
        batch_op.drop_index('idx_author_id')
        batch_op.drop_index('idx_author_knownas')
        batch_op.drop_index('idx_author_penname')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_book_author')
        batch_op.drop_index('idx_book_first_publish')
        batch_op.drop_index('idx_book_id')
        batch_op.drop_index('idx_book_title')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publ_closed', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('publ_summary', sa.Text(), nullable=True))
        batch_op.drop_index('idx_publisher_country')
        batch_op.drop_index('idx_publisher_id')
        batch_op.drop_index('idx_publisher_publ_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index('idx_publisher_publ_name', ['publ_name'], unique=False)
        batch_op.create_index('idx_publisher_id', ['id'], unique=False)
        batch_op.create_index('idx_publisher_country', ['publ_country'], unique=False)
        batch_op.drop_column('publ_summary')
        batch_op.drop_column('publ_closed')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_book_title', ['title'], unique=False)
        batch_op.create_index('idx_book_id', ['id'], unique=False)
        batch_op.create_index('idx_book_first_publish', ['first_publish'], unique=False)
        batch_op.create_index('idx_book_author', ['author'], unique=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index('idx_author_penname', ['penname'], unique=False)
        batch_op.create_index('idx_author_knownas', ['knownas'], unique=False)
        batch_op.create_index('idx_author_id', ['id'], unique=False)
        batch_op.create_index('idx_author_fullname', ['fullname'], unique=False)
        batch_op.create_index('idx_author_country', ['country'], unique=False)

    # ### end Alembic commands ###
