"""removed unique from book title

Revision ID: 775a8dc40ca7
Revises: ce4c9a7dfa75
Create Date: 2024-07-19 19:33:44.550979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775a8dc40ca7'
down_revision = 'ce4c9a7dfa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('books_title_key', ['title'])

    # ### end Alembic commands ###
