"""added co_author field in Book and changed delete author engine accordingly

Revision ID: a60b4db027df
Revises: 572580b89719
Create Date: 2024-07-21 13:14:59.851535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60b4db027df'
down_revision = '572580b89719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('co_author', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('co_author')

    # ### end Alembic commands ###
