"""added isbn13 in Book model

Revision ID: a9ab69a7b378
Revises: c631892c8475
Create Date: 2024-07-22 14:33:59.864979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ab69a7b378'
down_revision = 'c631892c8475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn13', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('isbn13')

    # ### end Alembic commands ###
