"""added name related fields and gender field in Author model

Revision ID: bf08f500f776
Revises: a60b4db027df
Create Date: 2024-07-22 04:29:01.922107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf08f500f776'
down_revision = 'a60b4db027df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name_pref', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name_suf', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('name_suf')
        batch_op.drop_column('name_pref')
        batch_op.drop_column('midname')

    # ### end Alembic commands ###
