"""removed unique from  email field in Author

Revision ID: ce4c9a7dfa75
Revises: 3a437c31ed66
Create Date: 2024-07-19 15:08:54.135127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4c9a7dfa75'
down_revision = '3a437c31ed66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('authors_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_unique_constraint('authors_email_key', ['email'])

    # ### end Alembic commands ###
