"""added fields in Author

Revision ID: d54fb5b66e67
Revises: 62de42483cf1
Create Date: 2024-07-19 05:03:45.224681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54fb5b66e67'
down_revision = '62de42483cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('born', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('born')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
