"""some more changes in AuthorPublisher table

Revision ID: e071b7fcfbae
Revises: 00a28621ed7f
Create Date: 2024-08-01 03:18:43.342263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e071b7fcfbae'
down_revision = '00a28621ed7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_publisher', schema=None) as batch_op:
        batch_op.drop_constraint('author_publisher_book_id_fkey', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_publisher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('author_publisher_book_id_fkey', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
