"""added Publisher table and appropriate relationships with Author and Book tables respectively

Revision ID: fa6ccc3333e1
Revises: 44d403843f2e
Create Date: 2024-07-31 16:27:57.425099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6ccc3333e1'
down_revision = '44d403843f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publ_name', sa.String(), nullable=False),
    sa.Column('publ_est', sa.String(), nullable=True),
    sa.Column('publ_country', sa.String(), nullable=True),
    sa.Column('publ_city', sa.String(), nullable=True),
    sa.Column('publ_address', sa.String(), nullable=True),
    sa.Column('publ_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publishers', ['publisher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('publisher_id')

    op.drop_table('author_publisher')
    op.drop_table('publishers')
    # ### end Alembic commands ###
